version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      # user: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - ./code:/var/www/html

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/webroot
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - "./code:/var/www/html"
      - "./code/cake4php.conf.tmpl:/etc/gotpl/presets/cake4php.conf.tmpl"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`app.${PROJECT_BASE_URL}`)'

  adminer:
    container_name: "${PROJECT_NAME}_adminer"
    image: wodby/adminer:$ADMINER_TAG
    environment:
      ## For PostgreSQL:
      ##      ADMINER_DEFAULT_DB_DRIVER: pgsql
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME

  ide:
    image: codercom/code-server:latest
    container_name: "${PROJECT_NAME}_ide"
    #user: coder -> id -u:id -
    command: --auth none
    volumes:
      - "./code:/home/coder/project"
      - "./coder/share/code-server:/home/coder/.local/share/code-server"
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${PROJECT_NAME}_ide.rule=Host(`ide.${PROJECT_BASE_URL}`)'
      - 'traefik.http.services.${PROJECT_NAME}_ide.loadbalancer.server.port=8080'
      - 'traefik.http.middlewares.mid1-${PROJECT_NAME}_ide.basicauth.users=${BASIC_AUTH}'
      - 'traefik.http.routers.${PROJECT_NAME}_ide.middlewares=mid1-${PROJECT_NAME}_ide@docker'

